before:
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - darwin
    goarch:
      - arm64
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
